apiVersion: v1
name: substrabac
home: https://substra.org/
version: 1.0.0-alpha.10
description: Main package for Substra
icon: https://avatars1.githubusercontent.com/u/38098422?s=200&v=4
sources:
  - https://github.com/SubstraFoudation/substrabac
maintainers:
  - name: ClementGautier
    email: clement@gautier.im
